const GET_ALL_RECEIPTS = 'GET_ALL_RECEIPTS';
const DELETE_RECEIPT = 'DELETE_RECEIPT';
const ADD_RECEIPT = 'ADD_RECEIPT';
const UPDATE_RECEIPT = 'UPDATE_RECEIPT';
const OPEN_ADD_FORM = 'OPEN_ADD_FORM';
const CLOSE_ADD_FORM = 'CLOSE_ADD_FORM';
const OPEN_UPDATE_FORM = 'OPEN_UPDATE_FORM';
const CLOSE_UPDATE_FORM = 'CLOSE_UPDATE_FORM';

export {
    GET_ALL_RECEIPTS,
    DELETE_RECEIPT,
    ADD_RECEIPT,
    UPDATE_RECEIPT,
    OPEN_ADD_FORM,
    CLOSE_ADD_FORM,
    OPEN_UPDATE_FORM,
    CLOSE_UPDATE_FORM
}